import { Candle, Language, Timeframe } from './types';

// Helper to generate some realistic looking random walk data for Gold
const startPrice = 2030.50;
let currentPrice = startPrice;

export const generateInitialData = (count: number, timeframe: Timeframe = '15m'): Candle[] => {
  const data: Candle[] = [];
  const now = new Date();
  
  let intervalMinutes = 15;
  switch(timeframe) {
      case '1m': intervalMinutes = 1; break;
      case '3m': intervalMinutes = 3; break;
      case '5m': intervalMinutes = 5; break;
      case '15m': intervalMinutes = 15; break;
      case '30m': intervalMinutes = 30; break;
      case '1H': intervalMinutes = 60; break;
      case '2H': intervalMinutes = 120; break;
      case '4H': intervalMinutes = 240; break;
      case '8H': intervalMinutes = 480; break;
      case '12H': intervalMinutes = 720; break;
      case '1D': intervalMinutes = 1440; break;
      case '3D': intervalMinutes = 4320; break;
      case '1W': intervalMinutes = 10080; break;
      case '1M': intervalMinutes = 43200; break;
  }

  for (let i = count; i > 0; i--) {
    const time = new Date(now.getTime() - i * intervalMinutes * 60 * 1000); 
    const move = (Math.random() - 0.5) * 2 * (intervalMinutes / 15); // Scale volatility by time
    const open = currentPrice;
    const close = open + move;
    const high = Math.max(open, close) + Math.random() * 0.5 * (intervalMinutes / 15);
    const low = Math.min(open, close) - Math.random() * 0.5 * (intervalMinutes / 15);
    
    currentPrice = close;
    
    let timeStr = '';
    // Format logic
    if (['1D', '3D', '1W', '1M'].includes(timeframe)) {
        timeStr = time.toLocaleDateString(undefined, { month: 'numeric', day: 'numeric' });
    } else {
        timeStr = time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    }

    data.push({
      time: timeStr,
      open,
      high,
      low,
      close
    });
  }
  return data;
};

export const INITIAL_BALANCE = 10000.00; // Mock 10k USDC
export const SYMBOL = "XAU/USDC";

export const TRANSLATIONS = {
  en: {
    trade: 'Trade',
    positions: 'Positions',
    orders: 'Orders',
    assets: 'Assets',
    long: 'Buy / Long',
    short: 'Sell / Short',
    market: 'Market',
    limit: 'Limit',
    cross: 'Cross',
    isolated: 'Isolated',
    leverage: 'Leverage',
    price: 'Price',
    entryPrice: 'Entry Price',
    size: 'Size',
    avail: 'Avail',
    margin: 'Margin',
    liqPrice: 'Liq Price',
    openPositions: 'Open Positions',
    noPositions: 'No active positions',
    closePos: 'Close Position',
    openOrders: 'Open Orders',
    orderHistory: 'History',
    noOrders: 'No orders',
    totalEquity: 'Total Equity',
    unrealizedPnL: 'Unrealized PnL',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    transfers: 'Transfers',
    history: 'Trade History',
    settings: 'Settings',
    funding: 'Cash Flow',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    disconnect: 'Disconnect Wallet',
    connect: 'Connect Wallet',
    network: 'Network',
    address: 'Address',
    confirm: 'Confirm',
    max: 'Max',
    addMargin: 'Adjust Margin',
    add: 'Add',
    remove: 'Remove',
    cancel: 'Cancel',
    confirmAction: 'Confirm',
    marginRatio: 'Margin Ratio',
    maintMargin: 'Maint. Margin',
    marginBal: 'Margin Bal.',
    riskWarning: 'Warning: High liquidation risk!',
    depositAddress: 'Deposit Address',
    amount: 'Amount',
    iHaveTransferred: 'I Have Transferred',
    lastPrice: 'Last Price',
    markPrice: 'Mark Price',
    fundingRate: 'Funding Rate',
    countdown: 'Countdown',
    mode: 'Mode',
    securityCenter: 'Security Center',
    chartLine: 'Line',
    chartCandle: 'Candle',
    chartDepth: 'Depth',
    tabOrderBook: 'Order Book',
    tabRecentTrades: 'Recent Trades',
    time: 'Time',
    qty: 'Qty',
    marginRequired: 'Margin Required',
    closeAll: 'Close All',
    cancelAll: 'Cancel All',
    depositVaultTitle: 'Deposit via Vault Contract',
    approving: 'Approving USDC...',
    depositing: 'Depositing to Vault...',
    depositSuccess: 'Deposit Successful',
    totalPerpValue: 'Total Perp Value',
    withdrawVaultTitle: 'Withdraw from Vault',
    withdrawing: 'Withdrawing from Vault...',
    withdrawSuccess: 'Withdrawal Successful',
    walletBalance: 'Wallet Balance',
    filled: 'Filled',
    status: 'Status',
    statusFilled: 'Filled',
    statusCancelled: 'Cancelled',
    confirmCloseAll: 'Confirm Close All',
    confirmCloseAllMsg: 'Are you sure you want to close all positions at market price?',
    before: 'Before',
    after: 'After',
    currentMargin: 'Current Margin',
    afterMargin: 'After Margin',
    estLiqPrice: 'Liq Price',
    maxRemove: 'Max Removable',
    change24h: '24h Chg',
    vol24h: '24h Vol',
    openInterest: 'Open Interest',
    all: 'All',
    positionMode: 'Position Mode',
    oneWayMode: 'One-Way Mode',
    hedgeMode: 'Hedge Mode',
    positionModeError: 'U-margin contract holds positions, position mode adjustment not supported.',
    tradeHistoryFields: {
        pair: 'Pair',
        side: 'Side',
        price: 'Price',
        qty: 'Qty',
        fee: 'Fee',
        realizedPnl: 'Realized PnL',
        value: 'Value'
    },
    cashFlowTypes: {
        TRANSACTION_FEE: 'Transaction Fee',
        FUNDING_FEE: 'Funding Fee',
        REALIZED_PNL: 'Realized PnL',
        LIQUIDATION_FEE: 'Liquidation Fee'
    },
    notifications: {
        orderPlaced: 'Order Placed Successfully',
        positionClosed: 'Position Closed Successfully',
        orderCancelled: 'Order Cancelled Successfully',
        positionsClosed: 'All Positions Closed',
        ordersCancelled: 'All Orders Cancelled',
        depositSuccess: 'Deposit Successful',
        withdrawSuccess: 'Withdrawal Successful',
        marginUpdated: 'Margin Updated Successfully',
        inputAmountReq: 'Please enter a valid amount',
        insufficientWallet: 'Insufficient wallet balance',
        insufficientAvail: 'Insufficient available balance',
        positionModeUpdated: 'Position Mode Updated'
    },
    fundingDetails: {
      title: 'Funding Rate Details',
      interval: 'Interval',
      intervalValue: '1 Hour',
      direction: 'Direction',
      directionValue: 'Long pays Short',
      interestRate: 'Interest Rate',
      apr: 'Estimated APR',
      description: 'Funding fees are exchanged between long and short positions every hour to keep the contract price aligned with the spot price.'
    }
  },
  'zh-CN': {
    trade: '交易',
    positions: '仓位',
    orders: '委托',
    assets: '账户',
    long: '买入 / 做多',
    short: '卖出 / 做空',
    market: '市价',
    limit: '限价',
    cross: '全仓',
    isolated: '逐仓',
    leverage: '杠杆',
    price: '价格',
    entryPrice: '开仓价格',
    size: '数量',
    avail: '可用',
    margin: '保证金',
    liqPrice: '强平价格',
    openPositions: '当前持仓',
    noPositions: '暂无持仓',
    closePos: '平仓',
    openOrders: '当前委托',
    orderHistory: '历史委托',
    noOrders: '暂无委托',
    totalEquity: '账户权益',
    unrealizedPnL: '未实现盈亏',
    deposit: '充值',
    withdraw: '提现',
    transfers: '充提记录',
    history: '历史成交',
    settings: '设置',
    funding: '资金流水',
    language: '语言',
    theme: '主题',
    light: '浅色',
    dark: '深色',
    disconnect: '退出登录',
    connect: '连接钱包',
    network: '网络',
    address: '地址',
    confirm: '确认',
    max: '最大',
    addMargin: '调整保证金',
    add: '增加',
    remove: '提取',
    cancel: '取消',
    confirmAction: '确认',
    marginRatio: '保证金率',
    maintMargin: '维持保证金',
    marginBal: '保证金余额',
    riskWarning: '警告：强平风险较高！',
    depositAddress: '充值地址',
    amount: '金额',
    iHaveTransferred: '我已转账',
    lastPrice: '最新价',
    markPrice: '标记价格',
    fundingRate: '资金费率',
    countdown: '倒计时',
    mode: '模式',
    securityCenter: '安全中心',
    chartLine: '分时',
    chartCandle: 'K线',
    chartDepth: '深度',
    tabOrderBook: '订单薄',
    tabRecentTrades: '最新成交',
    time: '时间',
    qty: '数量',
    marginRequired: '占用保证金',
    closeAll: '市价全平',
    cancelAll: '全部取消',
    depositVaultTitle: '合约充值',
    approving: '正在授权 USDC...',
    depositing: '正在存入金库...',
    depositSuccess: '充值成功',
    totalPerpValue: '持仓总价值',
    withdrawVaultTitle: '金库提现',
    withdrawing: '正在从金库提现...',
    withdrawSuccess: '提现成功',
    walletBalance: '钱包可用余额',
    filled: '成交',
    status: '状态',
    statusFilled: '完全成交',
    statusCancelled: '已取消',
    confirmCloseAll: '确认全部平仓',
    confirmCloseAllMsg: '您确定要以市价平掉所有当前持仓吗？',
    before: '调整前',
    after: '调整后',
    currentMargin: '当前保证金',
    afterMargin: '调整后保证金',
    estLiqPrice: '强平价',
    maxRemove: '最大可提取',
    change24h: '24h 涨跌',
    vol24h: '24h 成交额',
    openInterest: '未平仓合约',
    all: '全部',
    positionMode: '持仓模式',
    oneWayMode: '单向持仓',
    hedgeMode: '双向持仓',
    positionModeError: 'U本位合约存在持仓，不支持调整仓位模式。',
    tradeHistoryFields: {
        pair: '交易对',
        side: '方向',
        price: '成交价格',
        qty: '成交数量',
        fee: '交易费',
        realizedPnl: '已实现盈亏',
        value: '成交金额'
    },
    cashFlowTypes: {
        TRANSACTION_FEE: '交易手续费',
        FUNDING_FEE: '资金费',
        REALIZED_PNL: '已实现盈亏',
        LIQUIDATION_FEE: '清算费'
    },
    notifications: {
        orderPlaced: '下单成功',
        positionClosed: '平倉成功',
        orderCancelled: '委托已取消',
        positionsClosed: '所有仓位已平倉',
        ordersCancelled: '所有委托已取消',
        depositSuccess: '充值成功',
        withdrawSuccess: '提现成功',
        marginUpdated: '保证金调整成功',
        inputAmountReq: '请输入有效金额',
        insufficientWallet: '钱包余额不足',
        insufficientAvail: '可提现余额不足',
        positionModeUpdated: '持仓模式已更新'
    },
    fundingDetails: {
      title: '资金费率详情',
      interval: '收费间隔',
      intervalValue: '1 小时',
      direction: '支付方向',
      directionValue: '多头 支付 空头',
      interestRate: '基础利率',
      apr: '预估年化',
      description: '资金费率每小时在多空双方之间交换，以锚定现货价格。'
    }
  },
  'zh-TW': {
    trade: '交易',
    positions: '倉位',
    orders: '委託',
    assets: '帳戶',
    long: '買入 / 做多',
    short: '賣出 / 做空',
    market: '市價',
    limit: '限價',
    cross: '全倉',
    isolated: '逐倉',
    leverage: '槓桿',
    price: '價格',
    entryPrice: '開倉價格',
    size: '數量',
    avail: '可用',
    margin: '保證金',
    liqPrice: '強平價格',
    openPositions: '當前持倉',
    noPositions: '暫無持倉',
    closePos: '平倉',
    openOrders: '當前委託',
    orderHistory: '歷史委託',
    noOrders: '暫無委託',
    totalEquity: '帳戶權益',
    unrealizedPnL: '未實現盈虧',
    deposit: '充值',
    withdraw: '提現',
    transfers: '充提記錄',
    history: '歷史成交',
    settings: '設置',
    funding: '資金流水',
    language: '語言',
    theme: '主題',
    light: '淺色',
    dark: '深色',
    disconnect: '退出登錄',
    connect: '連接錢包',
    network: '網絡',
    address: '地址',
    confirm: '確認',
    max: '最大',
    addMargin: '調整保證金',
    add: '增加',
    remove: '提取',
    cancel: '取消',
    confirmAction: '確認',
    marginRatio: '保證金率',
    maintMargin: '維持保證金',
    marginBal: '保證金餘額',
    riskWarning: '警告：強平風險較高！',
    depositAddress: '充值地址',
    amount: '金額',
    iHaveTransferred: '我已轉帳',
    lastPrice: '最新價',
    markPrice: '標記價格',
    fundingRate: '資金費率',
    countdown: '倒計時',
    mode: '模式',
    securityCenter: '安全中心',
    chartLine: '分時',
    chartCandle: 'K線',
    chartDepth: '深度',
    tabOrderBook: '訂單簿',
    tabRecentTrades: '最新成交',
    time: '時間',
    qty: '數量',
    marginRequired: '占用保證金',
    closeAll: '市價全平',
    cancelAll: '全部取消',
    depositVaultTitle: '合約充值',
    approving: '正在授權 USDC...',
    depositing: '正在存入金庫...',
    depositSuccess: '充值成功',
    totalPerpValue: '持倉總價值',
    withdrawVaultTitle: '金庫提現',
    withdrawing: '正在從金庫提現...',
    withdrawSuccess: '提現成功',
    walletBalance: '錢包可用餘額',
    filled: '成交',
    status: '狀態',
    statusFilled: '完全成交',
    statusCancelled: '已取消',
    confirmCloseAll: '確認全部平倉',
    confirmCloseAllMsg: '您確定要以市價平掉所有當前持倉嗎？',
    before: '調整前',
    after: '調整後',
    currentMargin: '當前保證金',
    afterMargin: '調整後保證金',
    estLiqPrice: '強平價',
    maxRemove: '最大可提取',
    change24h: '24h 漲跌',
    vol24h: '24h 成交額',
    openInterest: '未平仓合约',
    all: '全部',
    positionMode: '持倉模式',
    oneWayMode: '單向持倉',
    hedgeMode: '雙向持倉',
    positionModeError: 'U本位合約存在持倉，不支持調整倉位模式。',
    tradeHistoryFields: {
        pair: '交易對',
        side: '方向',
        price: '成交價格',
        qty: '成交數量',
        fee: '交易費',
        realizedPnl: '已實現盈虧',
        value: '成交金額'
    },
    cashFlowTypes: {
        TRANSACTION_FEE: '交易手續費',
        FUNDING_FEE: '資金費',
        REALIZED_PNL: '已實現盈虧',
        LIQUIDATION_FEE: '清算費'
    },
    notifications: {
        orderPlaced: '下單成功',
        positionClosed: '平倉成功',
        orderCancelled: '委託已取消',
        positionsClosed: '所有倉位已平倉',
        ordersCancelled: '所有委託已取消',
        depositSuccess: '充值成功',
        withdrawSuccess: '提現成功',
        marginUpdated: '保證金調整成功',
        inputAmountReq: '請輸入有效金額',
        insufficientWallet: '錢包餘額不足',
        insufficientAvail: '可提現餘額不足',
        positionModeUpdated: '持倉模式已更新'
    },
    fundingDetails: {
      title: '資金費率詳情',
      interval: '收費間隔',
      intervalValue: '1 小時',
      direction: '支付方向',
      directionValue: '多頭 支付 空頭',
      interestRate: '基礎利率',
      apr: '預估年化',
      description: '資金費率每小時在多空雙方之間交換，以錨定現貨價格。'
    }
  }
};