
import { Candle, Language, Timeframe, MarketInfo } from './types';

const startPrice = 2030.50;
let currentPrice = startPrice;

export const generateInitialData = (count: number, timeframe: Timeframe = '15m'): Candle[] => {
  const data: Candle[] = [];
  const now = new Date();
  
  let intervalMinutes = 15;
  switch(timeframe) {
      case '1m': intervalMinutes = 1; break;
      case '3m': intervalMinutes = 3; break;
      case '5m': intervalMinutes = 5; break;
      case '15m': intervalMinutes = 15; break;
      case '30m': intervalMinutes = 30; break;
      case '1H': intervalMinutes = 60; break;
      case '2H': intervalMinutes = 120; break;
      case '4H': intervalMinutes = 240; break;
      case '8H': intervalMinutes = 480; break;
      case '12H': intervalMinutes = 720; break;
      case '1D': intervalMinutes = 1440; break;
      case '3D': intervalMinutes = 4320; break;
      case '1W': intervalMinutes = 10080; break;
      case '1M': intervalMinutes = 43200; break;
  }

  for (let i = count; i > 0; i--) {
    const time = new Date(now.getTime() - i * intervalMinutes * 60 * 1000); 
    const move = (Math.random() - 0.5) * 2 * (intervalMinutes / 15);
    const open = currentPrice;
    const close = open + move;
    const high = Math.max(open, close) + Math.random() * 0.5 * (intervalMinutes / 15);
    const low = Math.min(open, close) - Math.random() * 0.5 * (intervalMinutes / 15);
    currentPrice = close;
    let timeStr = '';
    if (['1D', '3D', '1W', '1M'].includes(timeframe)) {
        timeStr = time.toLocaleDateString(undefined, { month: 'numeric', day: 'numeric' });
    } else {
        timeStr = time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    }
    data.push({ time: timeStr, open, high, low, close });
  }
  return data;
};

export const INITIAL_BALANCE = 10000.00;
export const SYMBOL = "XAUUSDC";

export const MOCK_MARKETS: MarketInfo[] = [
  { symbol: 'XAUUSDC', name: 'Gold', lastPrice: 2023.91, change24h: 2.56, volume24h: 2950000, fundingRate: 0.0050, leverage: 20 },
  { symbol: 'BTCUSDC', name: 'Bitcoin', lastPrice: 65482.12, change24h: -7.52, volume24h: 2452938421, fundingRate: 0.0100, leverage: 50 },
  { symbol: 'ETHUSDC', name: 'Ethereum', lastPrice: 3452.85, change24h: 4.82, volume24h: 1252938421, fundingRate: -0.0025, leverage: 50 },
  { symbol: 'SOLUSDC', name: 'Solana', lastPrice: 142.52, change24h: -5.12, volume24h: 852938421, fundingRate: 0.0042, leverage: 20 },
  { symbol: 'XAUUSDC', name: 'Silver', lastPrice: 24.52, change24h: 0.45, volume24h: 52938421, fundingRate: 0.0010, leverage: 20 },
];

export const TRANSLATIONS = {
  en: {
    trade: 'Trade',
    positions: 'Positions',
    orders: 'Orders',
    assets: 'Assets',
    long: 'Buy / Long',
    short: 'Sell / Short',
    longLabel: 'Long',
    shortLabel: 'Short',
    market: 'Market',
    limit: 'Limit',
    cross: 'Cross',
    isolated: 'Isolated',
    leverage: 'Leverage',
    price: 'Price',
    entryPrice: 'Entry Price',
    size: 'Size',
    totalSize: 'Total',
    avail: 'Account Balance',
    margin: 'Margin',
    liqPrice: 'Liq Price',
    roi: 'ROI',
    openPositions: 'Open Positions',
    noPositions: 'No active positions',
    closePos: 'Close',
    openOrders: 'Open Orders',
    orderHistory: 'History',
    noOrders: 'No orders',
    totalEquity: 'Total Equity',
    unrealizedPnL: 'Unrealized PnL',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    transfers: 'Transfers',
    history: 'Trade History',
    settings: 'Settings',
    funding: 'Cash Flow',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    disconnect: 'Disconnect Wallet',
    connect: 'Connect Wallet',
    network: 'Network',
    currency: 'Currency',
    address: 'Address',
    confirm: 'Confirm',
    quickSwap: 'Quick Swap',
    estReceived: 'Est. Received',
    withdrawFee: 'Withdraw Fee',
    max: 'Max',
    addMargin: 'Adjust Margin',
    add: 'Add',
    remove: 'Remove',
    cancel: 'Cancel',
    confirmAction: 'Confirm',
    marginRatio: 'Margin Ratio',
    maintMargin: 'Maint. Margin',
    marginBal: 'Margin Bal.',
    riskWarning: 'Warning: High liquidation risk!',
    depositAddress: 'Deposit Address',
    amount: 'Amount',
    quantity: 'Quantity',
    iHaveTransferred: 'I Have Transferred',
    lastPrice: 'Last Price',
    markPrice: 'Mark Price',
    fundingRate: 'Funding Rate',
    countdown: 'Countdown',
    mode: 'Mode',
    securityCenter: 'Security Center',
    chartLine: 'Line',
    chartCandle: 'Candle',
    chartDepth: 'Depth',
    tabOrderBook: 'Order Book',
    tabRecentTrades: 'Recent Trades',
    time: 'Time',
    qty: 'Qty',
    marginRequired: 'Margin Required',
    closeAll: 'Close All',
    cancelAll: 'Cancel All',
    depositVaultTitle: 'Deposit via Vault Contract',
    approving: 'Approving {currency}...',
    depositing: 'Depositing to Vault...',
    depositSuccess: 'Deposit Successful',
    totalPerpValue: 'Total Perp Value',
    withdrawVaultTitle: 'Withdraw from Vault',
    withdrawing: 'Withdrawing from Vault...',
    withdrawSuccess: 'Withdrawal Successful',
    walletBalance: 'Wallet Balance',
    filled: 'Filled',
    status: 'Status',
    statusFilled: 'Filled',
    statusPartialFilled: 'Partial',
    statusCancelled: 'Cancelled',
    statusExpired: 'Expired',
    confirmCloseAll: 'Confirm Close All',
    confirmCloseAllMsg: 'Are you sure you want to close all positions at market price?',
    before: 'Before',
    after: 'After',
    currentMargin: 'Current Margin',
    afterMargin: 'After Margin',
    estLiqPrice: 'Liq Price',
    maxRemove: 'Max Removable',
    maxPosition: 'Max Position',
    change24h: '24h Chg',
    vol24h: '24h Vol',
    openInterest: 'Open Interest',
    all: 'All',
    positionMode: 'Position Mode',
    oneWayMode: 'One-Way Mode',
    hedgeMode: 'Hedge Mode',
    positionModeError: 'U-margin contract holds positions, position mode adjustment not supported.',
    searchPlaceholder: 'Search...',
    depositWarning: 'You are interacting directly with the Vault Smart Contract on Arbitrum. Ensure you have sufficient ETH for gas fees.',
    withdrawWarning: 'Withdrawals interact directly with the Vault contract. Funds will be returned to your connected wallet address: {address}',
    orderConfirm: 'Order Confirmation',
    popupNotify: 'Popup Notification',
    dontShowAgain: 'Don\'t show again',
    contract: 'Contract',
    direction: 'Side',
    explorer: 'Explorer',
    marketList: {
        contract: 'Contract',
        lastPrice: 'Last Price',
        change: '24h Chg',
        volume: '24h Vol',
        funding: 'Funding'
    },
    tradeHistoryFields: { pair: 'Pair', side: 'Side', price: 'Price', qty: 'Qty', fee: 'Fee', realizedPnl: 'Realized PnL', value: 'Value' },
    cashFlowTypes: { TRANSACTION_FEE: 'Fee', FUNDING_FEE: 'Funding', REALIZED_PNL: 'PnL', LIQUIDATION_FEE: 'Liq Fee' },
    transferStatuses: { COMPLETED: 'Completed', PENDING: 'Pending', REJECTED: 'Rejected', CANCELLED: 'Cancelled' },
    notifications: { orderPlaced: 'Success', positionClosed: 'Closed', orderCancelled: 'Cancelled', positionsClosed: 'All Closed', ordersCancelled: 'All Cancelled', depositSuccess: 'Deposit OK', withdrawSuccess: 'Withdraw OK', marginUpdated: 'Margin OK', inputAmountReq: 'Invalid Amount', insufficientWallet: 'Low Wallet', insufficientAvail: 'Low Bal', positionModeUpdated: 'Mode OK' },
    fundingDetails: { title: 'Funding Info', interval: 'Interval', intervalValue: '1h', direction: 'Side', directionValue: 'Long -> Short', interestRate: 'Funding Rate', estimatedApr: 'Estimated APR', apr: 'APR' },
    closeOperation: { title: 'Close Position', tradingPair: 'Trading Pair', estPnL: 'Est. PnL', positionSize: 'Position Size' },
    connection: {
        desc: 'Connect your secure wallet to deposit funds, trade perpetual contracts, and manage your portfolio.',
        selectWallet: 'Select Wallet',
        sigRequest: 'Signature Request',
        reject: 'Reject',
        sign: 'Sign',
        verifying: 'Verifying',
        connecting: 'Connecting',
        msgToSign: 'Message to sign',
        secureInfo: 'Secure & Encrypted Connection',
        approveIn: 'Please approve connection in'
    },
    appNotifications: {
        deposit: { title: 'Deposit Successful', content: 'You have successfully recharged {amount} USDC.' },
        withdraw: { title: 'Withdrawal Successful', content: 'Successfully withdrawn {amount} USDC to {address} (Arbitrum), estimated 1 minute.' },
        orderSuccess: { title: 'Order Submitted', content: 'Successfully submitted {symbol} {side} {type} order.\nPrice ${price} | Size {size} XAU | Leverage {leverage}x' },
        marketFilled: { title: 'Market Order Filled', content: 'Market {side} {size} XAU filled completely.\nAvg Price ${price} | Fee ${fee}' },
        limitFilled: { title: 'Limit Order Filled', content: 'Your open order filled!\n{side} {size} XAU @ ${price} | Fee ${fee}' },
        posClosed: { title: 'Position Closed', content: 'Successfully closed {symbol} {side}.\nClosed {size} XAU | PnL +${pnl}' },
        posReduced: { title: 'Position Reduced', content: 'Successfully reduced {symbol} {side}, reduced {size} XAU.\nRemaining {remaining} XAU | PnL +${pnl}' },
        liquidated: { title: 'Position Liquidated', content: 'Your {symbol} {side} position triggered liquidation. Liq Price ${price}, Fee ${fee} deducted.' },
        marginUpdated: { title: 'Margin Adjusted', content: 'Position margin for {symbol} updated by {amount} USDC.' }
    }
  },
  'zh-CN': {
    trade: '交易',
    positions: '仓位',
    orders: '委托',
    assets: '账户',
    long: '买入 / 做多',
    short: '卖出 / 做空',
    longLabel: '多头',
    shortLabel: '空头',
    market: '市价',
    limit: '限价',
    cross: '全仓',
    isolated: '逐仓',
    leverage: '杠杆',
    price: '价格',
    entryPrice: '开仓价格',
    size: '数量',
    totalSize: '总量',
    avail: '账户余额',
    margin: '保证金',
    liqPrice: '清算价格',
    roi: '收益率',
    openPositions: '当前持仓',
    noPositions: '暂无持仓',
    closePos: '平仓',
    openOrders: '当前委托',
    orderHistory: '历史委托',
    noOrders: '暂无委托',
    totalEquity: '账户权益',
    unrealizedPnL: '未实现盈亏',
    deposit: '充值',
    withdraw: '提现',
    transfers: '充提记录',
    history: '历史成交',
    settings: '设置',
    funding: '资金流水',
    language: '语言',
    theme: '主题',
    light: '浅色',
    dark: '深色',
    disconnect: '退出登录',
    connect: '连接钱包',
    network: '网络',
    currency: '币种',
    address: '地址',
    confirm: '确认',
    quickSwap: '闪兑',
    estReceived: '预估到账',
    withdrawFee: '提现手续费',
    max: '最大',
    addMargin: '调整保证金',
    add: '增加',
    remove: '提取',
    cancel: '取消',
    confirmAction: '确认',
    marginRatio: '保证金比率',
    maintMargin: '维持保证金',
    marginBal: '保证金余额',
    riskWarning: '警告：清算风险较高！',
    depositAddress: '充值地址',
    amount: '金额',
    quantity: '数量',
    iHaveTransferred: '我已转账',
    lastPrice: '最新价',
    markPrice: '标记价格',
    fundingRate: '资金费率',
    countdown: '倒计时',
    mode: '模式',
    securityCenter: '安全中心',
    chartLine: '分时',
    chartCandle: 'K线',
    chartDepth: '深度',
    tabOrderBook: '订单薄',
    tabRecentTrades: '最新成交',
    time: '时间',
    qty: '数量',
    marginRequired: '占用保证金',
    closeAll: '市价全平',
    cancelAll: '全部取消',
    depositVaultTitle: '合约充值',
    approving: '正在授权 {currency}...',
    depositing: '正在存入金库...',
    depositSuccess: '充值成功',
    totalPerpValue: '持仓价值',
    withdrawVaultTitle: '金库提现',
    withdrawing: '正在从金库提现...',
    withdrawSuccess: '提现成功',
    walletBalance: '钱包可用余额',
    filled: '成交',
    status: '状态',
    statusFilled: '完全成交',
    statusPartialFilled: '部分成交',
    statusCancelled: '已取消',
    statusExpired: '已过期',
    confirmCloseAll: '确认全部平仓',
    confirmCloseAllMsg: '您确定要以市价平掉所有当前持仓吗？',
    before: '调整前',
    after: '调整后',
    currentMargin: '当前保证金',
    afterMargin: '调整后保证金',
    estLiqPrice: '清算价格',
    maxRemove: '最大可提取',
    maxPosition: '最大持仓',
    change24h: '24h 涨跌',
    vol24h: '24h 成交额',
    openInterest: '未平仓合约',
    all: '全部',
    positionMode: '持仓模式',
    oneWayMode: '单向持仓',
    hedgeMode: '双向持仓',
    positionModeError: 'U本位合约存在持仓，不支持调整仓位模式。',
    searchPlaceholder: '搜索...',
    depositWarning: '您正在直接与 Arbitrum 上的金库智能合约交互。请确保您有足够的 ETH 用于支付 Gas 费用。',
    withdrawWarning: '提现直接与金库合约交互。资金将返还至您连接的钱包地址：{address}',
    orderConfirm: '订单确认',
    popupNotify: '弹出通知',
    dontShowAgain: '不再提示',
    contract: '合约',
    direction: '方向',
    explorer: '浏览器',
    marketList: {
        contract: '合约',
        lastPrice: '最新价格',
        change: '24h 涨跌幅',
        volume: '24h 成交额',
        funding: '资金费率'
    },
    tradeHistoryFields: { pair: '交易对', side: '方向', price: '价格', qty: '数量', fee: '费用', realizedPnl: '盈亏', value: '金额' },
    cashFlowTypes: { TRANSACTION_FEE: '手续费', FUNDING_FEE: '资金费', REALIZED_PNL: '盈亏', LIQUIDATION_FEE: '清算费' },
    transferStatuses: { COMPLETED: '已完成', PENDING: '审核中', REJECTED: '已拒绝', CANCELLED: '已取消' },
    notifications: { orderPlaced: '成功', positionClosed: '已平', orderCancelled: '已撤', positionsClosed: '全平', ordersCancelled: '全撤', depositSuccess: '成功', withdrawSuccess: '成功', marginUpdated: '成功', inputAmountReq: '金额错误', insufficientWallet: '余额不足', insufficientAvail: '不足', positionModeUpdated: '成功' },
    fundingDetails: { title: '详情', interval: '间隔', intervalValue: '1h', direction: '方向', directionValue: '多付空', interestRate: '资金费率', estimatedApr: '预估 APR', apr: 'APR' },
    closeOperation: { title: '平仓', tradingPair: '交易对', estPnL: '预估盈亏', positionSize: '持仓数量' },
    connection: {
        desc: '连接您的安全钱包以存入资金、交易永续合约并管理您的投资组合。',
        selectWallet: '选择钱包',
        sigRequest: '签名请求',
        reject: '拒绝',
        sign: '签名',
        verifying: '验证中',
        connecting: '连接中',
        msgToSign: '待签名消息',
        secureInfo: '安全且加密的连接',
        approveIn: '请在以下钱包中确认连接：'
    },
    appNotifications: {
        deposit: { title: '充值成功', content: '您已成功充值 {amount} USDC，请查看。' },
        withdraw: { title: '提现成功', content: '您已成功提现 {amount} USDC 至 {address} (Arbitrum)，预计 1 分钟到账。' },
        orderSuccess: { title: '下单成功', content: '您已成功提交 {symbol} {side} {type}单\n价格 ${price} | 数量 {size} XAU | 杠杆 {leverage}x' },
        marketFilled: { title: '市价单已完全成交', content: '市价{side} {size} XAU 已完全成交\n平均成交价 ${price} | 手续费 ${fee}' },
        limitFilled: { title: '限价单已完全成交', content: '您的挂单已完全成交！\n{side} {size} XAU @ ${price} | 手续费 ${fee}' },
        posClosed: { title: '仓位已平仓', content: '您已成功平仓 {symbol} {side}\n平仓数量 {size} XAU | 实现盈亏 +${pnl}' },
        posReduced: { title: '仓位已减仓', content: '已成功减仓 {symbol} {side}，减仓 {size} XAU\n剩余仓位 {remaining} XAU | 实现盈亏 +${pnl}' },
        liquidated: { title: '仓位已清算', content: '您的 {symbol} {side} 仓位已触发清算，清算价格 ${price}，已扣除 ${fee} 清算罚金。' },
        marginUpdated: { title: '保证金已调整', content: '{symbol} 仓位保证金已变动 {amount} USDC。' }
    }
  },
  'zh-TW': {
    trade: '交易',
    positions: '倉位',
    orders: '委託',
    assets: '帳戶',
    long: '買入 / 做多',
    short: '賣出 / 做空',
    longLabel: '多頭',
    shortLabel: '空頭',
    market: '市價',
    limit: '限價',
    cross: '全倉',
    isolated: '逐倉',
    leverage: '槓桿',
    price: '價格',
    entryPrice: '開倉價格',
    size: '數量',
    totalSize: '總量',
    avail: '帳戶餘額',
    margin: '保證金',
    liqPrice: '清算價格',
    roi: '收益率',
    openPositions: '當前持倉',
    noPositions: '暫無持倉',
    closePos: '平倉',
    openOrders: '當前委託',
    orderHistory: '歷史委託',
    noOrders: '暫無委託',
    totalEquity: '帳戶權益',
    unrealizedPnL: '未實現盈虧',
    deposit: '充值',
    withdraw: '提現',
    transfers: '充提記錄',
    history: '歷史成交',
    settings: '設置',
    funding: '資金流水',
    language: '語言',
    theme: '主題',
    light: '淺色',
    dark: '深色',
    disconnect: '退出登錄',
    connect: '連接錢包',
    network: '網絡',
    currency: '幣種',
    address: '地址',
    confirm: '確認',
    quickSwap: '閃兌',
    estReceived: '預估到帳',
    withdrawFee: '提現手續費',
    max: '最大',
    addMargin: '調整保證金',
    add: '增加',
    remove: '提取',
    cancel: '取消',
    confirmAction: '確認',
    marginRatio: '保證金比率',
    maintMargin: '維持保證金',
    marginBal: '保證金餘額',
    riskWarning: '警告：清算風險較高！',
    depositAddress: '充值地址',
    amount: '金額',
    quantity: '數量',
    iHaveTransferred: '我已轉帳',
    lastPrice: '最新價',
    markPrice: '標記價格',
    fundingRate: '資金費率',
    countdown: '倒計時',
    mode: '模式',
    securityCenter: '安全中心',
    chartLine: '分時',
    chartCandle: 'K線',
    chartDepth: '深度',
    tabOrderBook: '訂單簿',
    tabRecentTrades: '最新成交',
    time: '時間',
    qty: '數量',
    marginRequired: '占用保證金',
    closeAll: '市價全平',
    cancelAll: '全部取消',
    depositVaultTitle: '合約充值',
    approving: '正在授權 {currency}...',
    depositing: '正在存入金庫...',
    depositSuccess: '充值成功',
    totalPerpValue: '持倉價值',
    withdrawVaultTitle: '金庫提現',
    withdrawing: '正在從金庫提現...',
    withdrawSuccess: '提現成功',
    walletBalance: '錢包可用餘額',
    filled: '成交',
    status: '狀態',
    statusFilled: '完全成交',
    statusPartialFilled: '部分成交',
    statusCancelled: '已取消',
    statusExpired: '已過期',
    confirmCloseAll: '確認全部平倉',
    confirmCloseAllMsg: '您確定要以市價平掉所有當前持倉嗎？',
    before: '調整前',
    after: '調整後',
    currentMargin: '當前保證金',
    afterMargin: '調整後保證金',
    estLiqPrice: '清算價格',
    maxRemove: '最大可提取',
    maxPosition: '最大持倉',
    change24h: '24h 漲跌',
    vol24h: '24h 成交額',
    openInterest: '未平仓合约',
    all: '全部',
    positionMode: '持倉模式',
    oneWayMode: '單向持倉',
    hedgeMode: '雙向持倉',
    positionModeError: 'U本位合約存在持倉，不支持調整倉位模式。',
    searchPlaceholder: '搜索...',
    depositWarning: '您正在直接與 Arbitrum 上的金庫智能合約交互。請確保您有足夠的 ETH 用於支付 Gas 費用。',
    withdrawWarning: '提現直接與金庫合約交互。資金將返還至您連接的錢包地址：{address}',
    orderConfirm: '訂單確認',
    popupNotify: '彈出通知',
    dontShowAgain: '不再提示',
    contract: '合約',
    direction: '方向',
    explorer: '瀏覽器',
    marketList: {
        contract: '合約',
        lastPrice: '最新價格',
        change: '24h 漲跌幅',
        volume: '24h 成交額',
        funding: '資金費率'
    },
    tradeHistoryFields: { pair: '交易對', side: '方向', price: '價格', qty: '數量', fee: '費用', realizedPnl: '盈虧', value: '金額' },
    cashFlowTypes: { TRANSACTION_FEE: '手續費', FUNDING_FEE: '資金費', REALIZED_PNL: '盈虧', LIQUIDATION_FEE: '清算費' },
    transferStatuses: { COMPLETED: '已完成', PENDING: '審核中', REJECTED: '已拒絕', CANCELLED: '已取消' },
    notifications: { orderPlaced: '成功', positionClosed: '已平', orderCancelled: '已撤', positionsClosed: '全平', ordersCancelled: '全撤', depositSuccess: '成功', withdrawSuccess: '成功', marginUpdated: '成功', inputAmountReq: '金額錯誤', insufficientWallet: '餘額不足', insufficientAvail: '不足', positionModeUpdated: '成功' },
    fundingDetails: { title: '詳情', interval: '間隔', intervalValue: '1h', direction: '方向', directionValue: '多付空', interestRate: '資金費率', estimatedApr: '預估 APR', apr: 'APR' },
    closeOperation: { title: '平倉', tradingPair: '交易對', estPnL: '預估盈虧', positionSize: '持倉數量' },
    connection: {
        desc: '連接您的安全錢包以存入資金、交易永續合約並管理您的投資組合。',
        selectWallet: '選擇錢包',
        sigRequest: '簽名請求',
        reject: '拒絕',
        sign: '簽名',
        verifying: '驗證中',
        connecting: '連接中',
        msgToSign: '待簽名消息',
        secureInfo: '安全且加密的連接',
        approveIn: '請在以下錢包中確認連接：'
    },
    appNotifications: {
        deposit: { title: '充值成功', content: '您已成功充值 {amount} USDC，請查看。' },
        withdraw: { title: '提現成功', content: '您已成功提現 {amount} USDC 至 {address} (Arbitrum)，預計 1 分鐘到帳。' },
        orderSuccess: { title: '下單成功', content: '您已成功提交 {symbol} {side} {type}單\n價格 ${price} | 數量 {size} XAU | 杠杆 {leverage}x' },
        marketFilled: { title: '市價單已完全成交', content: '市價{side} {size} XAU 已完全成交\n平均成交價 ${price} | 手續費 ${fee}' },
        limitFilled: { title: '限價單已完全成交', content: '您的掛單已完全成交！\n{side} {size} XAU @ ${price} | 手續費 ${fee}' },
        posClosed: { title: '倉位已平倉', content: '您已成功平倉 {symbol} {side}\n平倉數量 {size} XAU | 實現盈虧 +${pnl}' },
        posReduced: { title: '倉位已減倉', content: '已成功減倉 {symbol} {side}，減倉 {size} XAU\n餘倉位 {remaining} XAU | 實現盈虧 +${pnl}' },
        liquidated: { title: '倉位已清算', content: '您的 {symbol} {side} 倉位已觸發清算，清算價格 ${price}，已扣除 ${fee} 清算罰金。' },
        marginUpdated: { title: '保證金已調整', content: '{symbol} 倉位保證金已變動 {amount} USDC。' }
    }
  }
};
